/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import zanshin.dsl.dsl.DslPackage;
import zanshin.dsl.dsl.Success;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Success</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuccessImpl extends TestTypeImpl implements Success
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuccessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.SUCCESS;
  }

} //SuccessImpl
