/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import zanshin.dsl.dsl.DslPackage;
import zanshin.dsl.dsl.TestType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Test Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link zanshin.dsl.dsl.impl.TestTypeImpl#getSimulationType <em>Simulation Type</em>}</li>
 *   <li>{@link zanshin.dsl.dsl.impl.TestTypeImpl#isArray <em>Array</em>}</li>
 *   <li>{@link zanshin.dsl.dsl.impl.TestTypeImpl#getLength <em>Length</em>}</li>
 *   <li>{@link zanshin.dsl.dsl.impl.TestTypeImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TestTypeImpl extends MinimalEObjectImpl.Container implements TestType
{
  /**
   * The default value of the '{@link #getSimulationType() <em>Simulation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimulationType()
   * @generated
   * @ordered
   */
  protected static final String SIMULATION_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSimulationType() <em>Simulation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimulationType()
   * @generated
   * @ordered
   */
  protected String simulationType = SIMULATION_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #isArray() <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isArray()
   * @generated
   * @ordered
   */
  protected static final boolean ARRAY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isArray() <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isArray()
   * @generated
   * @ordered
   */
  protected boolean array = ARRAY_EDEFAULT;

  /**
   * The default value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected static final int LENGTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected int length = LENGTH_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.TEST_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSimulationType()
  {
    return simulationType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimulationType(String newSimulationType)
  {
    String oldSimulationType = simulationType;
    simulationType = newSimulationType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.TEST_TYPE__SIMULATION_TYPE, oldSimulationType, simulationType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isArray()
  {
    return array;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setArray(boolean newArray)
  {
    boolean oldArray = array;
    array = newArray;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.TEST_TYPE__ARRAY, oldArray, array));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLength()
  {
    return length;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLength(int newLength)
  {
    int oldLength = length;
    length = newLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.TEST_TYPE__LENGTH, oldLength, length));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.TEST_TYPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.TEST_TYPE__SIMULATION_TYPE:
        return getSimulationType();
      case DslPackage.TEST_TYPE__ARRAY:
        return isArray();
      case DslPackage.TEST_TYPE__LENGTH:
        return getLength();
      case DslPackage.TEST_TYPE__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.TEST_TYPE__SIMULATION_TYPE:
        setSimulationType((String)newValue);
        return;
      case DslPackage.TEST_TYPE__ARRAY:
        setArray((Boolean)newValue);
        return;
      case DslPackage.TEST_TYPE__LENGTH:
        setLength((Integer)newValue);
        return;
      case DslPackage.TEST_TYPE__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.TEST_TYPE__SIMULATION_TYPE:
        setSimulationType(SIMULATION_TYPE_EDEFAULT);
        return;
      case DslPackage.TEST_TYPE__ARRAY:
        setArray(ARRAY_EDEFAULT);
        return;
      case DslPackage.TEST_TYPE__LENGTH:
        setLength(LENGTH_EDEFAULT);
        return;
      case DslPackage.TEST_TYPE__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.TEST_TYPE__SIMULATION_TYPE:
        return SIMULATION_TYPE_EDEFAULT == null ? simulationType != null : !SIMULATION_TYPE_EDEFAULT.equals(simulationType);
      case DslPackage.TEST_TYPE__ARRAY:
        return array != ARRAY_EDEFAULT;
      case DslPackage.TEST_TYPE__LENGTH:
        return length != LENGTH_EDEFAULT;
      case DslPackage.TEST_TYPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (simulationType: ");
    result.append(simulationType);
    result.append(", array: ");
    result.append(array);
    result.append(", length: ");
    result.append(length);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //TestTypeImpl
