/*
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import zanshin.dsl.ui.internal.DslActivator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("zanshin.dsl.Dsl");
	}

}
