/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>command Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link zanshin.dsl.dsl.commandBlock#getTesttype <em>Testtype</em>}</li>
 *   <li>{@link zanshin.dsl.dsl.commandBlock#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see zanshin.dsl.dsl.DslPackage#getcommandBlock()
 * @model
 * @generated
 */
public interface commandBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Testtype</b></em>' containment reference list.
   * The list contents are of type {@link zanshin.dsl.dsl.TestType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Testtype</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Testtype</em>' containment reference list.
   * @see zanshin.dsl.dsl.DslPackage#getcommandBlock_Testtype()
   * @model containment="true"
   * @generated
   */
  EList<TestType> getTesttype();

  /**
   * Returns the value of the '<em><b>Message</b></em>' containment reference list.
   * The list contents are of type {@link zanshin.dsl.dsl.Log}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' containment reference list.
   * @see zanshin.dsl.dsl.DslPackage#getcommandBlock_Message()
   * @model containment="true"
   * @generated
   */
  EList<Log> getMessage();

} // commandBlock
