/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commands</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see zanshin.dsl.dsl.DslPackage#getCommands()
 * @model
 * @generated
 */
public interface Commands extends EObject
{
} // Commands
