/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see zanshin.dsl.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.dsl.zanshin/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = zanshin.dsl.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.ModelImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Dsl</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DSL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.ProjectImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 1;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.TypeImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getType()
   * @generated
   */
  int TYPE = 2;

  /**
   * The feature id for the '<em><b>Simulation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__SIMULATION_TYPE = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__LENGTH = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 3;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.SuccessImpl <em>Success</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.SuccessImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getSuccess()
   * @generated
   */
  int SUCCESS = 3;

  /**
   * The feature id for the '<em><b>Simulation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUCCESS__SIMULATION_TYPE = TYPE__SIMULATION_TYPE;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUCCESS__ARRAY = TYPE__ARRAY;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUCCESS__LENGTH = TYPE__LENGTH;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUCCESS__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Success</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUCCESS_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.FailureImpl <em>Failure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.FailureImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getFailure()
   * @generated
   */
  int FAILURE = 4;

  /**
   * The feature id for the '<em><b>Simulation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAILURE__SIMULATION_TYPE = TYPE__SIMULATION_TYPE;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAILURE__ARRAY = TYPE__ARRAY;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAILURE__LENGTH = TYPE__LENGTH;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAILURE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Failure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAILURE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.TestQuantityImpl <em>Test Quantity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.TestQuantityImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getTestQuantity()
   * @generated
   */
  int TEST_QUANTITY = 5;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_QUANTITY__NUMBER = 0;

  /**
   * The number of structural features of the '<em>Test Quantity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_QUANTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.ScopeImpl <em>Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.ScopeImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getScope()
   * @generated
   */
  int SCOPE = 6;

  /**
   * The feature id for the '<em><b>Project</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE__PROJECT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE__NAME = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE__LENGTH = 2;

  /**
   * The feature id for the '<em><b>Testquantity</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE__TESTQUANTITY = 3;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE__COMMANDS = 4;

  /**
   * The number of structural features of the '<em>Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link zanshin.dsl.dsl.impl.CommandsImpl <em>Commands</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see zanshin.dsl.dsl.impl.CommandsImpl
   * @see zanshin.dsl.dsl.impl.DslPackageImpl#getCommands()
   * @generated
   */
  int COMMANDS = 7;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS__TYPE = 0;

  /**
   * The number of structural features of the '<em>Commands</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see zanshin.dsl.dsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link zanshin.dsl.dsl.Model#getDsl <em>Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dsl</em>'.
   * @see zanshin.dsl.dsl.Model#getDsl()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Dsl();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see zanshin.dsl.dsl.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Project#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see zanshin.dsl.dsl.Project#getImportedNamespace()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see zanshin.dsl.dsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Type#getSimulationType <em>Simulation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Simulation Type</em>'.
   * @see zanshin.dsl.dsl.Type#getSimulationType()
   * @see #getType()
   * @generated
   */
  EAttribute getType_SimulationType();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Type#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see zanshin.dsl.dsl.Type#isArray()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Array();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Type#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see zanshin.dsl.dsl.Type#getLength()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Length();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see zanshin.dsl.dsl.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Success <em>Success</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Success</em>'.
   * @see zanshin.dsl.dsl.Success
   * @generated
   */
  EClass getSuccess();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Failure <em>Failure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Failure</em>'.
   * @see zanshin.dsl.dsl.Failure
   * @generated
   */
  EClass getFailure();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.TestQuantity <em>Test Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Quantity</em>'.
   * @see zanshin.dsl.dsl.TestQuantity
   * @generated
   */
  EClass getTestQuantity();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.TestQuantity#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see zanshin.dsl.dsl.TestQuantity#getNumber()
   * @see #getTestQuantity()
   * @generated
   */
  EAttribute getTestQuantity_Number();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Scope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scope</em>'.
   * @see zanshin.dsl.dsl.Scope
   * @generated
   */
  EClass getScope();

  /**
   * Returns the meta object for the containment reference '{@link zanshin.dsl.dsl.Scope#getProject <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Project</em>'.
   * @see zanshin.dsl.dsl.Scope#getProject()
   * @see #getScope()
   * @generated
   */
  EReference getScope_Project();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Scope#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see zanshin.dsl.dsl.Scope#getName()
   * @see #getScope()
   * @generated
   */
  EAttribute getScope_Name();

  /**
   * Returns the meta object for the attribute '{@link zanshin.dsl.dsl.Scope#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see zanshin.dsl.dsl.Scope#getLength()
   * @see #getScope()
   * @generated
   */
  EAttribute getScope_Length();

  /**
   * Returns the meta object for the containment reference list '{@link zanshin.dsl.dsl.Scope#getTestquantity <em>Testquantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Testquantity</em>'.
   * @see zanshin.dsl.dsl.Scope#getTestquantity()
   * @see #getScope()
   * @generated
   */
  EReference getScope_Testquantity();

  /**
   * Returns the meta object for the containment reference list '{@link zanshin.dsl.dsl.Scope#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see zanshin.dsl.dsl.Scope#getCommands()
   * @see #getScope()
   * @generated
   */
  EReference getScope_Commands();

  /**
   * Returns the meta object for class '{@link zanshin.dsl.dsl.Commands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commands</em>'.
   * @see zanshin.dsl.dsl.Commands
   * @generated
   */
  EClass getCommands();

  /**
   * Returns the meta object for the containment reference '{@link zanshin.dsl.dsl.Commands#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see zanshin.dsl.dsl.Commands#getType()
   * @see #getCommands()
   * @generated
   */
  EReference getCommands_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.ModelImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Dsl</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DSL = eINSTANCE.getModel_Dsl();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.ProjectImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__IMPORTED_NAMESPACE = eINSTANCE.getProject_ImportedNamespace();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.TypeImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Simulation Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__SIMULATION_TYPE = eINSTANCE.getType_SimulationType();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__ARRAY = eINSTANCE.getType_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__LENGTH = eINSTANCE.getType_Length();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.SuccessImpl <em>Success</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.SuccessImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getSuccess()
     * @generated
     */
    EClass SUCCESS = eINSTANCE.getSuccess();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.FailureImpl <em>Failure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.FailureImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getFailure()
     * @generated
     */
    EClass FAILURE = eINSTANCE.getFailure();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.TestQuantityImpl <em>Test Quantity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.TestQuantityImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getTestQuantity()
     * @generated
     */
    EClass TEST_QUANTITY = eINSTANCE.getTestQuantity();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_QUANTITY__NUMBER = eINSTANCE.getTestQuantity_Number();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.ScopeImpl <em>Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.ScopeImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getScope()
     * @generated
     */
    EClass SCOPE = eINSTANCE.getScope();

    /**
     * The meta object literal for the '<em><b>Project</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCOPE__PROJECT = eINSTANCE.getScope_Project();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCOPE__NAME = eINSTANCE.getScope_Name();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCOPE__LENGTH = eINSTANCE.getScope_Length();

    /**
     * The meta object literal for the '<em><b>Testquantity</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCOPE__TESTQUANTITY = eINSTANCE.getScope_Testquantity();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCOPE__COMMANDS = eINSTANCE.getScope_Commands();

    /**
     * The meta object literal for the '{@link zanshin.dsl.dsl.impl.CommandsImpl <em>Commands</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see zanshin.dsl.dsl.impl.CommandsImpl
     * @see zanshin.dsl.dsl.impl.DslPackageImpl#getCommands()
     * @generated
     */
    EClass COMMANDS = eINSTANCE.getCommands();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDS__TYPE = eINSTANCE.getCommands_Type();

  }

} //DslPackage
