/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Failure</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see zanshin.dsl.dsl.DslPackage#getFailure()
 * @model
 * @generated
 */
public interface Failure extends TestType
{
} // Failure
