/**
 * generated by Xtext 2.10.0
 */
package zanshin.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Success</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see zanshin.dsl.dsl.DslPackage#getSuccess()
 * @model
 * @generated
 */
public interface Success extends Type
{
} // Success
